services:
    rc0wwc0-195635897712:
        image: 'rc0wwc0:79187c3ec7be8628901dafda811d4412082f59f9'
        container_name: rc0wwc0-195635897712
        restart: unless-stopped
        expose:
            - '3000'
        networks:
            coolify:
                aliases:
                    - rc0wwc0-195635897712
        mem_limit: '0'
        memswap_limit: '0'
        mem_swappiness: 60
        mem_reservation: '0'
        cpus: 0.0
        cpu_shares: 1024
        env_file:
            - .env
        healthcheck:
            test:
                - CMD-SHELL
                - 'curl -s -X GET -f http://localhost:3000/ > /dev/null || wget -q -O- http://localhost:3000/ > /dev/null || exit 1'
            interval: 5s
            timeout: 5s
            retries: 10
            start_period: 5s
        labels:
            - traefik.enable=true
            - traefik.http.middlewares.gzip.compress=true
            - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
            - traefik.http.routers.http-0-rc0wwc0.entryPoints=http
            - traefik.http.routers.http-0-rc0wwc0.middlewares=gzip
            - 'traefik.http.routers.http-0-rc0wwc0.rule=Host(`rc0wwc0.95.216.215.248.sslip.io`) && PathPrefix(`/`)'
            - traefik.http.routers.http-0-rc0wwc0.service=http-0-rc0wwc0
            - traefik.http.routers.http-1-rc0wwc0.entryPoints=http
            - traefik.http.routers.http-1-rc0wwc0.middlewares=redirect-to-https
            - 'traefik.http.routers.http-1-rc0wwc0.rule=Host(`newmeit.ru`) && PathPrefix(`/`)'
            - traefik.http.routers.http-1-rc0wwc0.service=http-1-rc0wwc0
            - traefik.http.routers.https-1-rc0wwc0.entryPoints=https
            - traefik.http.routers.https-1-rc0wwc0.middlewares=gzip
            - 'traefik.http.routers.https-1-rc0wwc0.rule=Host(`newmeit.ru`) && PathPrefix(`/`)'
            - traefik.http.routers.https-1-rc0wwc0.service=https-1-rc0wwc0
            - traefik.http.routers.https-1-rc0wwc0.tls.certresolver=letsencrypt
            - traefik.http.routers.https-1-rc0wwc0.tls=true
            - traefik.http.services.http-0-rc0wwc0.loadbalancer.server.port=3000
            - traefik.http.services.http-1-rc0wwc0.loadbalancer.server.port=3000
            - traefik.http.services.https-1-rc0wwc0.loadbalancer.server.port=3000
            - 'caddy_0.encode=zstd gzip'
            - 'caddy_0.handle_path.0_reverse_proxy={{upstreams 3000}}'
            - 'caddy_0.handle_path=/*'
            - caddy_0.header=-Server
            - 'caddy_0.try_files={path} /index.html /index.php'
            - 'caddy_0=http://rc0wwc0.95.216.215.248.sslip.io'
            - 'caddy_1.encode=zstd gzip'
            - 'caddy_1.handle_path.1_reverse_proxy={{upstreams 3000}}'
            - 'caddy_1.handle_path=/*'
            - caddy_1.header=-Server
            - 'caddy_1.try_files={path} /index.html /index.php'
            - 'caddy_1=https://newmeit.ru'
            - caddy_ingress_network=coolify
            - coolify.managed=true
            - coolify.version=4.0.0-beta.379
            - coolify.applicationId=19
            - coolify.type=application
            - coolify.name=rc0wwc0
            - coolify.pullRequestId=0
networks:
    coolify:
        external: true
        name: coolify
        attachable: true
